### ISSUE TITLE
Bug report: uploading kml files after dragging and dropping

### ISSUE THREAD

**Issue by davidedwardjensen** [unep-grid/map-x-mgl#164]
I tried to upload the 3 attached files into MapX after successfully dragging and dropping them into the map window. This generated an immediate pop up window saying I had discovered a bug and that an automatic notice would be sent to Fred. I just wanted to follow-up here to send the files,

[infrastructure.zip](https://github.com/fxi/map-x-mgl/files/1565400/infrastructure.zip)

**Comment by thomaspiller** [comment]
I checked the KML files and it turns out that they contain multiple layers with different attribute tables. 
The conversion from KML to GeoJSON (with ogr) returns an error (only the first layer included in the KML is converted).

A possible solution to add such KML files in MapX database would be to have a pop-up window that list all the layers included in the KML (like in QGIS). The user will have to choose one layer to be added as a new source.

![shutter_20171221](https://user-images.githubusercontent.com/19908801/34258113-d2f4b5d8-e65c-11e7-8171-ba4458fc3b6c.png)

**Comment by thomaspiller** [comment]
As requested, I will write a small report about these KML files and I will post it here as a soon as possible. I'm very busy right now so it will probably be for the end of next week.

**Comment by antobenve** [comment]
Hi @thomaspiller is this issue still relevant or was it fixed? I see you had to report on this but I don't see the report. Maybe the issue was previously fixed?
