### ISSUE TITLE
Story maps cannot advance using swipe on a mobile phone or tablet....

### ISSUE THREAD

**Issue by davidedwardjensen** [unep-grid/map-x-mgl#190]
It would be good if story maps could advance slides either by clicking with the mouse on a PC, or by using the normal swipe screen function on an iphone or ipad. The user experience of trying to actually click one of the tiny buttons on an iphone doesnt work very well.

**Comment by fxi** [comment]
The story map module was designed with touch screen and scroll in mind. The idea is to feel that your scroll movement will drive a nice animation (see the draft : http://output.jsbin.com/tupulit). Then support for control by keystroke has been added. Then fixed layout has also been added. Scrolling is less fun since. I think people are maybe missing the point : they don’t create their stories to be fun to read or good looking. They simply put many tons of pictures fullscreen to hide the beautiful map. No parallax, no camera play, no slide or map animation. That’s maybe why the scroll is boring. Adding swipe will not solve anything — my biased opinion — but I can do it.
