### ISSUE TITLE
The download data button should always appear

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#254]
*Source: Google sheet shared with UNDP & PCDMB*

The download data button should always appear regarding the type of view (vector,raster...).
If the data cannot be downloaded then the reason should be explained.
For data that can be downloaded, the metadata and the licence should be present in the .zip archive.

**Comment by MarionPlanque** [comment]
@fxi is this pb solved? can I close this topic?

**Comment by fxi** [comment]
Nope, I'm not done with it.

**Comment by MarionPlanque** [comment]
Ok!

**Comment by fxi** [comment]
So, there is multiple things here:

- [ ] Implement raster download. Maybe a link to wms could do the trick ?
- [ ] The current message "Can't be downloaded" is not clear enough.. Need that someone write down a better message ?
- [ ] License should be integrated in the metadata. Which license ? License from metadata or MapX license ? A separate doc ? Need more info for this.
- [ ] Metatada should be integrated in the download zip. The format will be JSON, as no clear description is provided.

**Comment by antobenve** [comment]
@fxi 
> Implement raster download. Maybe a link to wms could do the trick ?
I don't think so because WMS requests only serve tiles. WCS would be the right request for downloading rasters. 
Either we provide a link in the configuration window of a raster view to the WCS request or we might find a way to interact with GeoServer. In this case I wonder if it wouldn't worth having GeoSolutions on this as they could produce something capable to make MapX interact with GeoServer. This might also be useful for the geolocalisation of a dataset in the map (as it is possible for vector views already with the button "Zoom to features").

> License should be integrated in the metadata. Which license ? License from metadata or MapX license ? A separate doc ? Need more info for this.

The metadata of the rasters that are published in the GeoServer are published in the GeoNetwork in ISO format. Among all fields there are some about licence. If I'm not wrong the interns were working on making MapX and ISO formats compatible so that the metadata of raster views could be displayed in a similar way to how the vector views do.

**Comment by thomaspiller** [comment]
Since then, the strategy has been revised and the download tool has been extended to the raster view. I close this issue as it is no longer relevant.
