### ISSUE TITLE
Story map: error message about a missing view

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#352]
In [this](https://app.mapx.org?project=MX-M5H-L8I-1AL-ZSQ-HXD&views=MX-54YWZ-08GC6-A47US) story map, when playing the story map an error message appears slide 6 and no data layer is shown on the map. The message says: "Error during layer evaluation :Error: Layer with id "MX-CHSJK-KS0AV-7G5GV_@_5" does not exist on this map.".
However, when playing the story map in the other way (from the end to the beginning), all the layers are on the map and no error message appears.
_NB_: Slide 5 et slide 6 have the same layers used, plus 2 extra other layers used in slide 6
_NB bis_: The two extra layers may be layers visible/editable only by a third person, Gianluca (to be confirmed)

**Comment by antobenve** [comment]
The view id is just "MX-CHSJK-KS0AV-7G5GV" and it exists. I don't know how the "_@_5" got in. This might be the reason why the view is not found.

**Comment by fxi** [comment]
`_@_5` is the suffix of the fifth layer of the view which is produced by the fifth rule defined in your style.
The layer defined here is the layer of the [mapbox gl style](https://www.mapbox.com/mapbox-gl-js/style-spec/#layers). 
We still use one layer per rule instead of mapbox gl data driven style, as it does not exists at the time I've wrote the module.
So, MapX try to remove a layer that have already been removed and this produce an error.

**Comment by MarionPlanque** [comment]
So, just to be sure I understood, are you saying that the story map is calling a layer that has been deleted in the project?

**Comment by fxi** [comment]
Not at all.
This is an internal issue and I have to take care of it.

**Comment by MarionPlanque** [comment]
Ok. I think this is not hyper-urgent if you have other priorities. Just something maybe to keep in mind, and maybe explaining how not to have this bug happening again?
