### ISSUE TITLE
Problematic: shared views are necessarily public

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#361]
When a view is shared in another project (using the button share view OR "other project in which the view should be visible"), this view is automatically visible for public users, even though the "original" view is restricted for members or publishers only.

**Comment by antobenve** [comment]
IMHO, the restriction should apply to every project where a view is shared to.
The actual users that should be able to see the view in a project will depend on the role they have in that specific project.

**Comment by MarionPlanque** [comment]
I agree; it makes sense because in any case, the projects to which a user can add views to depend on the user's status in these projects

**Comment by antobenve** [comment]
@fxi I just realized that once a private view is shared to another project, not only it becomes public in the shared project (which we knew already), but it becomes public in the project where it is published too.

**Comment by fxi** [comment]
Ok.
The rule if that if the user has access to one view, in the current project or any other, if the view is present in the current project, it will be available for reading. I think this what's happening. Maybe it's wrong.
For now, shared views become public, so yes, public wherever the view is published. 
As I've already said, if there is a more restrictive pattern to follow, is someone provides a complete scenario of view visibility combination, I can maybe implement it : views of the story editor, views in stories, shared views, exported views, views in exported stories, etc. 
In all cases : a lot of issues are occurring because of the lack of sub-projects. When sub-projects will be implemented, a lot of sharing will not make sense anymore. A sub-project will have hierarchical user's right, it will be easier – I think – to propagate access rights through a hierarchical parent / children relation. 
What I will not do – for now – is enabling cross project view target management : it would be really heavy to process.

**Comment by antobenve** [comment]
Thanks @fxi. I partly agree with your idea that subprojects will improve the sharing management.
However, I still think that there may be cases of views that will be shared from a project to another project even when subprojects will exist (UNBIOLAB to WESR and viceversa for instance). 
I haven't been able to come up with a solid idea yet but I will think about it.

**Comment by MarionPlanque** [comment]
@antobenve I bring this topic back to your attention

**Comment by antobenve** [comment]
@MarionPlanque thanks! A solution that could solve this issue is identified in the frame of the subprojects development but we don't know when/if this development can start.

**Comment by thomaspiller** [comment]
The logic was changed lately. Views that are shared to other projects keep their read access and are no longer made public by default.
