### ISSUE TITLE
rev. 1.5.35 manual testing results

### ISSUE THREAD

**Issue by fxi** [unep-grid/map-x-mgl#378]
- [x] Project can't be removed in other language that english. 
     - To test  try to change or set a title in another language, and try to remove the project.
- [x] filters (bottom left panel).:
     - Not updated after view create
- [x] display metadata (i button): edit metadata button doesn't work.
- [x] Delete project when the title is not set in current language
- [x] modal windows don't resize after a click on a drop-down list.
- [x] download: the minimum character length should be 3 for the output filename.
- [x] "txt_too_short_min_5" when downloading a layer should be expressed in english

@antobenve @thomaspiller Please add your own finding bellow

**Comment by thomaspiller** [comment]
- [ ] display metadata (i button): edit metadata button doesn't work.
- [ ] modal windows don't resize after a click on a drop-down list.
- [ ] download: the minimum character length should be 3 for the output filename.
- [ ] area of visible features: value is not deleted when switching project.
- [ ] story maps: steps' numbers are displayed even after the story maps is closed. If another story map is open after, two rows of numbers are displayed.
- [ ] filter views by tags: the check symbol is removed when a view is clicked but the filter is still active.

**Comment by antobenve** [comment]
### Where not specified, bugs applies to both Firefox and Chrome in Win 7, online version v.1.5.35.
- [ ] pop up windows always shift towards right (check when creating a view where the confirmation message is)
- [ ] pix op is very slow in Firefox and makes the app lagging enormously (10s of seconds lags when the option "Highlight any visible feature" is on on )
- [ ] "txt_too_short_min_5" when downloading a layer should be expressed in english
- [ ] empty files are downloaded when data and selected country don't intersect at all. --> Blocks download when no data intersects like for "overlap utilities".
- [ ] story maps steps buttons during preview disappears when "Save" is clicked. To continue editing the story one must close it and re-open it in edit mode. 

#### Project deletion problem:
- [ ] Not possible to launch the "delete a project tool" if the title doesn't exist in the current language of the user. Adding a title in the json file of project configuration makes it possible.

#### Legends problems during export:
- [ ] Exported map is less zoomed in Chrome compared to Firefox and has a larger width. The result is odd (too short image compared to the height of the pdf). 
- [ ] Both Firefox and Chrome have arrow and legend below the map instead of on it.
Firefox:
![image](https://user-images.githubusercontent.com/30286565/50278405-33d07780-0447-11e9-9567-f2d6e6e27b9b.png)
Chrome:
![image](https://user-images.githubusercontent.com/30286565/50278426-40ed6680-0447-11e9-910a-999c15648910.png)

**Comment by antobenve** [comment]
#### Other legend export problems are still encountered in variable amount and form depending on the computer of the user in Chrome. No systematicity is detected. The list of problems is the one in #371 and has been updated with information related on error frequency and causalities.
As a synthesis, problems are:
- [ ] text is cut by "..." when not needed (Chrome, Win10)
- [ ] text is very small and not sharp (not readable) (Chrome, Win10)
- [ ] not more than 1 zip file is downloaded when "Print current" on more than 1 view on map --> MapX must be restarted to export a zip file again through "Print current" (Chrome, Win10)

**Comment by thomaspiller** [comment]
I close this issue as all remaining items are related to the map/pdf export. The soon to be released "map composer" should solve all of that.
