### ISSUE TITLE
New request: confirmation email when a membership request is accepted

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#400]
Would it be possible to inform the admin that invited a new user to a project when the user accepts the membership request?

In case the project has more than 1 admin, the email needs to be sent to the admin that performed the invitation of the external user.

This would avoid loosing track of all users that do not accept invitations in a short time frame and that must be upgraded to publishers.
Thanks

**Comment by fxi** [comment]
Yep, it's possible to add this to the current solution. It's an extra step after 

join request > accept > membership
or
invitation > accept > membership

I was thinking about a new way of keeping track of all notifications – emission, reception, read status and confirmations to get an idea of which message has been received, read and confirmed. This would give to administrators a clear view of what's going on : sender, recipient, number of retries, discarded... All confirmation link could also be short instead of containing a full encrypted object – used to keep track of sender, and invalidation timestamp, etc.  Example of what a short confirmation request could look like : https://api.mapx.org/get/confirm?code=f409hdkPwlks&accept=false.

**Comment by antobenve** [comment]
Thanks for the answer and the explanation. I think your concept is definitely more complete and useful compared to a simple alert email.
To have an idea of work charge, how long might it take to devleop your full concept? And how long might instead take the integration of alert emails that inform the admin that a user accepted an invitation?

**Comment by fxi** [comment]
This could be closed ?

**Comment by antobenve** [comment]
Yes, indeed.
