### ISSUE TITLE
Data download is not working

### ISSUE THREAD

**Issue by florianfranz** [unep-grid/map-x-mgl#409]
When trying to download data, the progress seems to be blocked and no error message is displayed (see image below), not allowing to actually download the data. Trying the same process on another computer, the download works but the files are empty (1Kb size SHP).

![downloadissue](https://user-images.githubusercontent.com/42937007/54598098-1c019300-4a38-11e9-8e7d-1fedd877035f.jpg)

**Comment by antobenve** [comment]
Hi @florianfranz , I get this message when I try to download that layer (with and without any selected country for clipping).
`Layer mx_wld_vector_fu25d_d8er6_mx73m( Biodiversity hotspots (Conservation International) ) has invalid geometry and can't be clipped by country. Please correct it, then try again`
This suggests that the layer is the problem.

However, you seem to have other problems we never encountered:
- logs are not displayed,
- download tool generates empty file when it should not.

Can you please define your browser and OS here?
Can you also please check what happens when you download a layer with correct geometries such as "Continuous Land-Sea Administrative Boundary" in the UNBiodiversityLab - World with no country selected? Please copy the log here if you see any.
Thanks

**Comment by florianfranz** [comment]
Hi @antobenve,

The screenshot in my first post is the same as any other layer i try to download (see image below for the "Continuous Land-Sea Administrative Boundary.

My OS is Windows 10 and downloading data was tried on Google Chrome (Version 72.0.3626.121) as well as on Microsoft Edge, with the same error.

![downloadissue2](https://user-images.githubusercontent.com/42937007/54599701-751ef600-4a3b-11e9-96df-8bb84e41c336.jpg)
"

**Comment by antobenve** [comment]
@florianfranz , thanks. Can you confirm that you managed to download the layer "Continuous Land-Sea Administrative Boundary" although your log windows remained empty?

**Comment by florianfranz** [comment]
@antobenve : I could manage to download the data

**Comment by antobenve** [comment]
Thanks @florianfranz .
Finally, I think that your problem is the logs that are not displayed.
