### ISSUE TITLE
Rewording of "Auto start story" in Share module

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#465]
The text about sharing a story map in autoStart mode, that is shown in the Share module, should be changed from "Auto start story" to  "**Share story map in play mode**"

**Comment by tdearden** [comment]
I suggest that the rewording contains the word "public" to make the purpose clear. Not sure that users will care about kiosk/play mode. 

Suggest: "**Share story map in public mode**"

**Comment by fxi** [comment]
I've decided to avoid "mode", "share" and "public"  because this option does not imply an alternate mode, it does not modify the sharing mechanism and if the view is not explicitly set as public, the fallback will be the same as any other views. 

Maybe there was a confusion with the "kiosk mode" which overwrite the reader's settings, does not start a server side application and render immediately whatever selected view.
 
The new label is "Play the story immediately after MapX is loaded.".

**Comment by antobenve** [comment]
I do like this choice. It is simple and clear.

**Comment by antobenve** [comment]
This was solved in the new version 1.6.23, the selected term being "Play the story immediately after MapX is loaded"
