### ISSUE TITLE
Download tool improvement

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#471]
It would be interesting if the download tool has the following options:
- download whole dataset _(already available)_
- clip by country(ies) using GAUL
  - simplified version _(already available)_
  - raw version
- clip by country(ies) using maritime boundaries (dataset to be identified)
- SQL query to export features based on a selection done in the attribute table

**Comment by scabecks** [comment]
The clip by country(ies) using maritime boundaries is a great idea, as is SQL queries by iso! There are always issues with clipping other datasets to any boundary (which are often built and clipped to some other boundary layer), particularly marine stuff as there are often lots of interesting features along coastlines one wants to capture as intact as possible. One way to deal with that is to use a admin layer that includes a seamless merge both land and marine areas (like the EEZ) so that there is no coastal marine boundary per se, so that in effect data that was already clipped to some coastline when made isn't clipped again along the coastline by another layer. If that make sense. The continuous land-sea admin boundary in UNBL is one way to do that (https://app.mapx.org?project=MX-GVQ-KL6-XTL-XFU-2QY&views=MX-45MO0-NJ5FA-HBUGA).

**Comment by antobenve** [comment]
I strongly approve Scott's proposition and suggest the continuous land-sea admin boundary in UNBL to be used in our download tool. If you find it reasonable too, @Thomas, can you update your initial list in order to include it? It could actually be a better option than the maritime layer option or make another one on its own.

**Comment by thomaspiller** [comment]
This development was requested for the UNBiodiversityLab and is no longer needed. I therefore close this issue.
