### ISSUE TITLE
WFS service not working - getcapabilities request not rendering xml

### ISSUE THREAD

**Issue by scabecks** [unep-grid/map-x-mgl#530]
Views with allowed publishing via WMS/WFS/WCS are unable to be found, and getcapabilities requests on the maxp geoserver (https://geoserver.mapx.org/geoserver/web/) return nothing (e.g., https://geoserver.mapx.org/geoserver/wfs?service=wfs&request=getcapabilities).

Browser: NA
OS: NA

**Comment by antobenve** [comment]
It seems there's a[ limit to 10 characters](https://docs.geoserver.org/latest/en/user/data/webadmin/workspaces.html#:~:text=The%20workspace%20name%20is%20limited,and%20may%20not%20contain%20space.) for the workspace names but it seems this causes issues.
On the contrary, I think that special characters like "@" are forbidden in workspaces names although I haven't found any confirmation online -> workspaces with less than 10 characters that contain "@" in the GeoServer datacore fail when being saved in the interface. 

Finally, this issue only cause problems when requesting the GetCapabilities of the WFS service because, as you can see from the linked examples, workspace's names are reported in the first line of the xml of the [WFS ](https://datacore.unepgrid.ch/geoserver/wfs?request=getcapabilities&service=wfs)service while they are not for the [WMS ](https://datacore.unepgrid.ch/geoserver/wms?request=getcapabilities&service=wms)one.

**Comment by antobenve** [comment]
This issue no longer exists due to changes in geoserver's structure.
