### ISSUE TITLE
Static link doesn't load any view if a specific view is in "views"

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#634]
The static link that is generated for a group of views in which the [Baseline Water Stress view](https://app.staging.mapx.org?project=MX-YBJ-YYF-08R-UUR-QW6&views=MX-Y3HWB-9IXHB-3AW3N&viewsOpen=MX-Y3HWB-9IXHB-3AW3N&language=en&) is present doesn't load any view on map nor on legend's panel.
[Static link](https://app.staging.mapx.org/static.html?views=MX-Y3HWB-9IXHB-3AW3N&zoomToViews=true&language=en&) to the Baseline Water Stress view.

The issue doesn't occur in [prod](https://app.mapx.org/static.html?views=MX-Y3HWB-9IXHB-3AW3N&zoomToViews=true&language=en&).

Version 1.8.0-alpha using Chrome 87.0.4280.88 on Windows 10

**Comment by fxi** [comment]
If you look in the network panel, you can see that a request is pending. It's the source summary. For this particular layer, the computation of the spatial summary takes a while because the data is really .. badly complex  : it's a raster covering the globe, which has been converted to vector, with.. no generalization. Probably the work of a student or GIS novice:
![image](https://user-images.githubusercontent.com/1196833/104215897-b450df00-5439-11eb-8d9e-eedb0d4c7658.png)
![image](https://user-images.githubusercontent.com/1196833/104216058-dd716f80-5439-11eb-9364-f64d557393f3.png)

The summary can't be instantaneous. We could make it faster using a more coarse approximation of the spatial summary. 

However, the summary is split in multiple part and cached. Subsequent requests are instantaneous, as long as it lives in the cache. In staging, it's flushed regularly. If the layer is altered, the cache is also lost.

**Comment by thomaspiller** [comment]
PostgreSQL configuration was optimized in November 2020 using [PGTune](https://pgtune.leopard.in.ua/#/). It seems that this had a negative effect on the performance of the database. The config was reinitialized when updating PostgreSQL to version 13.1. Since then the view loads as expected in static mode.
@antobenve I think this issue can be closed.

**Comment by antobenve** [comment]
yes yes yes, you're right.... I forgot that the issue was still open.
