### ISSUE TITLE
1.8.4-beta disconnection after 60 second if idle.

### ISSUE THREAD

**Issue by fxi** [unep-grid/map-x-mgl#645]
@thomaspiller reported a disconnection of mapx APP after 60 seconds using MapX 1.8.4 docker image during testing. It should not happen : except server errors and closing a tab, nothing can terminate a session.

This is extremely blocking and should be solved before pushing in prod. 

Here is was was reported so far :

os | browser | extension | antivirus | firewall | vpn | host | net | delay | consistant | reproducible | logs
-- |  -- | -- | -- | -- | -- | -- | -- | -- | --| -- | -- |
windows 10 Pro 20H2 |  chrome  88.0 | - | Windows Defender | system | NordVPN | staging | private | 60 | ✅ | ⛔  | <a href="#log1">1)</a>
windows 10 Pro 20H2 |  ff  84.0.2 | - | Windows Defender | system | NordVPN | staging | private | 60 | ✅ | ⛔  | 
windows 10 Pro 20H2 |  chrome  88.0 | - | Windows Defender | system | NordVPN | pro | private | 0 | ✅ | ✅  | 
mac os 10.15.17|  chrome 87.0 | - | - | system | - | staging | office | 0 | ✅ | ✅  |
mac os 10.15.17|  ff 84.0.2 | - | - | system | - | staging | office | 0 | ✅ | ✅   |
mac os 10.15.17|  opera 71.0| - | - | system | opera vpn | staging | office | 40 | ✅ | ✅   |
mac os 10.15.17|  opera 71.0|  - |- | system | opera vpn |prod | office | 0 | ✅ | ✅   |

( this table will be updated  )
delay of "0" means : did not disconnected for at least 20 minutes of idle time. 

<ul>
<li>1) <span id="log1">NA</span></li>
</ul>

**Comment by thomaspiller** [comment]
This issue was related to using a VPN (NordVPN) when working on MapX staging infrastructure.
When the VPN was activated (server located in Switzerland), there was a systematic disconnection after 60 seconds.
This was not reproducible on the production version of MapX.
Once the VPN disabled, I no longer suffered disconnections (MapX was stable for at least 5 minutes).
FYI, with the VPN enabled, I tested to use MapX staging with my browser in private mode and with my antivirus disabled and that did not solve the problem.

**Comment by thomaspiller** [comment]
As nothing has been reported regarding this issue for more than a year, I close it for now.
