### ISSUE TITLE
Some sdk methods doesn't resolve anymore

### ISSUE THREAD

**Issue by trepmag** [unep-grid/map-x-mgl#670]
Sdk Manager.ask() method doesn't resolve with the following identified methods:
- set_panel_left_visibility
- set_immersive_mode

This is probably a regression or removals following mapx 1.8.x version?...

The result is that some apps relying on the sdk might not work anymore because they are waiting on some promises to resolve:
- https://unepgrid.ch/playground/wesr-air-quality/
- https://unepgrid.ch/playground/teeb/
- ...

Example:
```js
const m = new Manager(...);

m.on('ready', async () => {
  await m.ask('set_panel_left_visibility'); // script stop here because promise doesn't return
  ...
});
```

Above apps can be quickly fixed by removing culprits instructions in their code.

On mapx side, sdk Manager.ask() should return even when using wrong methods (using reject()).

**Comment by fxi** [comment]
Thanks,

This sounds blocking. 

This has been marked as solved in #647 by @thomaspiller. I guess something new occurred since. 

Could this wait to be fixed on Monday ?

Notes :
- All basic tests passed,  but our tests cover only a few cases. We should move to standard tests system, which was the plan since you mentioned issues with the current one. 
- Immersive mode should now have the same behavior as the new 'closePanels=true' parameter.
- For the resolving part, the current implementation is incomplete, yes. It should reject if the message `success` is false, which should be the case if the resolver is not found or the timeout trigger before in a `promise.race`.

**Comment by trepmag** [comment]
Yes, from my point it's not urgent (I quick fixed on app side in mean time)...

**Comment by trepmag** [comment]
Hello, the issue appears to be still active (version 1.8.39-beta).

The following example illustrate this, showing the script stale while entering `await m.ask('set_immersive_mode', { toggle: true });`: https://codepen.io/trepmag/pen/eYWgKdr

Removing the `await` keyword allow to pass through the mentioned method but no immersive mode is applied!

This is also applicable to `set_panel_left_visibility` method...

**Comment by fxi** [comment]
It seems to be related to an issue with the built package... All tests pass and in dev mode, it works as expected

![mx_bug_sdk_immersive](https://user-images.githubusercontent.com/1196833/125613067-d68b2578-aeea-4f46-ba6f-dd569ecb206b.gif)

**Comment by fxi** [comment]
I found the issue : the sdk version is for 1.8.39-beta ( in staging ) while you requested a connexion to prod ( 1.8.17 ). The resolver will not work as expected :(

**Comment by fxi** [comment]
Working example:

https://jsfiddle.net/fxi/cy9rmwhe/2/

**Comment by fxi** [comment]
We could.. maybe.. having an "empty shell" module, with minimal set of methods. On load, it could update itself with the latest code or resolvers from the "worker" it tries to connect to ? Like a remote module.. 
Or use a route to deliver the built module:
`app.mapx.org/sdk.js` instead of `https://cdn.jsdelivr.net/npm/@fxi/mxsdk@1.8.39-beta/dist/mxsdk.umd.min.js` . The user code could then be invalid... 
Or at least warn that there is a version missmatch...

**Comment by trepmag** [comment]
Indeed, having the related sdk version by a "lookup" the mapx instance it must work with would be ideal!

**Comment by fxi** [comment]
By the way, the sdk warns about version missmatch, I totally forgot:
![image](https://user-images.githubusercontent.com/1196833/125651014-65960117-6f6f-4fd4-98a7-c88d34ec3f9e.png)

**Comment by trepmag** [comment]
Ah nice!... Btw it doesn't output with https://codepen.io/trepmag/pen/eYWgKdr ...

**Comment by fxi** [comment]
It's optional

```js
mapx.on('message', (message) => {
  if (message.level === 'log') {
    console.info(`%c 🤓 ${message.text}`, 'color: #76bbf7');
  } else if (message.level === 'message') {
    console.info(`%c 😎 ${message.text}`, 'color: #70e497');
  } else if (message.level === 'warning') {
    console.info(`%c 🥴 ${message.text}`, 'color: #d09c23');
  } else if (message.level === 'error') {
    console.info(`%c 🤬 ${message.text}`, 'color: #F00');
  }
});

```
![image](https://user-images.githubusercontent.com/1196833/125654191-0481cc63-2227-4e22-aab5-4a958c294f6f.png)

**Comment by fxi** [comment]
More compact version:

```js
m.on('message', (msg) => {
  switch (msg.level) {
    case 'log':
      return console.log(msg.text);
    case 'message':
      return console.info(msg.text);
    case 'warning':
      return console.warn(msg.text);
    case 'error':
      return console.error(msg.text);
    default:
      consol.log('unhandler msg', msg);
  }
});
```

**Comment by fxi** [comment]
MapX 1.9.0 has been released and this issue should be solved using the host https://app.mapx.org

**Comment by thomaspiller** [comment]
@trepmag if everything is ok now, could you close this issue please?

**Comment by trepmag** [comment]
Congratulation for the release! And this appears to be resolved... Thank you!

We might need to followup this with the sdk and mapx instance version mismatch with might popup later...
