### ISSUE TITLE
Style configuration bugs that especially affect items with symbols

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#777]
Vector view with point feature :
  
- [x] Item with symbol ( sprite ) in legend is 10 * size. On the map is maki-size * size * zoom factor * interpolation factor. E.g.

  - size 10 with maki-danger-15, zoom 0=1, zoom 22=1, scaleFactor =1. On the map, it will be 150px. In the legend, 100px.

    - [x] Option 1 (preferred) = size on map, size in legend = 10px

    - [ ] Option 2 = size on map, size on legend = 150px ( take in account the 15 in maki-danger-15)

- [x] Some symbols are not shown on map : previous rule's symbol is recycled,

- [x] Legend item do not match feature size on map,

- [ ] #779

**Comment by fxi** [comment]
I changed 3 things in the management of symbols:
1. The size defined in the rules correspond exactly to the size displayed on the map: extraction of raw data stored in mapbox gl, replacement of pixels from a temporary canvas, creation of a data URL. There are no more svg. This should ensure that the pixel density of the screen does not change the size. Using versions -11 and -15 of the maki symbols no longer changes the size of the object, but marginally its resolution (legend and map)
2. I replaced the 3 "geol" hatches with generated patterns (these IDs point to the new patterns that roughly look like). SVGs converted to sprites had a 1px margin added, and that made a visual shift). This is no longer the case now.
3. The anchor of the symbols is now at the bottom center: If we tilt the map and rotate, they point to the right place and rotate around the Y axis, instead of traveling anywhere.

![mx_style_symbole_size](https://user-images.githubusercontent.com/1196833/146797136-b5b1925d-75c1-434b-aafe-fd1dfbe2c0de.gif)
