### ISSUE TITLE
Features on map do not respond to dashboard sliders after a given time (miniCacheGet: timeout)

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#848]
Layers that should respond to dashboard sliders stop responding after a few seconds and trigger a `miniCacheGet: timeou` error.

It seems that layers are not properly removed from map by the slider anymore. Not sure if it's a dashboard problem or a new bug as the previous version of MapX could not filter the attribute table (#842 )

Example: https://app.mapx.org/static.html?language=en&views=MX-SDKP9-ZDXF8-4CBU0&zoomToViews=true&p=0&b=0&z=3.438&lat=32.077&lng=22.927&t3d=false&sat=false&theme=water_light 

Same view that can be used for testing: https://app.mapx.org/?language=en&project=MX-R2F-467-2PL-J9H-CCR&viewsListFlatMode=false&viewsOpen=MX-0YS02-WURMZ-LSMNP&viewsListFilterActivated=true&p=0&b=0&z=3.84&lat=42.083&lng=6.933&t3d=false&sat=false&theme=classic_light

**Comment by thomaspiller** [comment]
I didn't get the `miniCacheGet: timeout` error.
However, there are at least 2 problems with the code of this widget:
1. `const maxYear = 2016` while the data only goes up to 2015
2. layers are not removed from the map when a new year is selected in the slider. It seems that by adding to the `update` function this code snippet, the problem is solved:

    ```js
    if (viewLayers.length > 0) {
        h.removeLayersByPrefix({
            prefix: view.id
        });
    }
    ```

In addition, I noticed that the filters from the legend have a weird behavior and do not filter the elements of the map well.
@fxi Any idea? Could you take a look at it when you have a moment please? Thanks!

**Comment by antobenve** [comment]
Thanks for checking it.
I didn't realize there was another error (your point 1) as well and I believe the two are not related.

I've been reported other views with the same problem of layers not being removed (ex. [1](https://app.mapx.org/?project=MX-R2F-467-2PL-J9H-CCR&viewsOpen=MX-ILGL3-3JVRG-BQ7XP&viewsListFilterActivated=true), [2](https://app.mapx.org/?project=MX-R2F-467-2PL-J9H-CCR&viewsOpen=MX-M4O7D-67WRA-GPUB6&viewsListFilterActivated=true))
I wonder if we should fix this issue using your added code or if this should be fixed at the basis as it may affect other views as well.

**Comment by thomaspiller** [comment]
All the views you mention have the same code for the slider on the attributes/columns and the interaction with the map so it's no wonder they all have the same problem.

From what I see, the problem lies in the logic of the dashboard which bypasses the standard operation of MapX.
The dashboard must be corrected in each of these views.

At the MapX app level, I think the only thing that could be done is to develop a slider system on the attributes/columns of a view.  So it's not a small fix/improvement.

**Comment by fxi** [comment]
The way dashboards and custom code views work now is not optimal : it's very much sloppy. Code written here can't be tested, and if not properly written – missing promise, failing cleaning, etc.. – it can break stuff far down the line. Maybe a peer review process could "unlock" publication of that kind of views. 

We should probably re-develop those features inside an isolated context and only expose a set of methods like the ones from the SDK, or have a set of pre-build widgets, easy to use and configure, that could be part of the mapx source code.

For  the slider on attributes, that could be an option, but statistics, automatic styling, SLD, and everything that expect a single attribute could be impacted.

**Comment by thomaspiller** [comment]
@antobenve Is this still an issue?

**Comment by antobenve** [comment]
we can close it.
